API для обновления ролей пользователя + базовая обработка ошибок
valkrisd/UserManagementService pull request #1
Opened 2024-07-11 11:45 UTC by valkrisd

Реализация API для обновления ролей пользователя, а также базовая логика обработки ошибок при помощи @ControllerAdvice

2024-07-11 13:30 UTC, liroykaz requested changes

2024-07-11 13:30 UTC, liroykaz commented on src/main/java/com/niiazov/usermanagement/controllers/ProfilesController.java
> +        Profile profile = profilesService.findProfile(userId);
одна общая ошибка - использование маппера на этапе контроллера. Мы должны в сервисе брать ентити нужное из репозитория, выполнять какую-то логику на нем или если надо сразу в ДТО переводить через маппер. Но прокидывать на контроллер ентити бэд практис

2024-07-11 13:30 UTC, liroykaz commented on src/main/java/com/niiazov/usermanagement/controllers/ProfilesController.java
> +        Profile profile = profilesService.findProfile(userId);
в других контроллерах просьба поправить

2024-07-11 13:30 UTC, liroykaz commented on src/main/java/com/niiazov/usermanagement/controllers/RolesController.java
> +    @Autowired
мелочь, но лучше придерживаться стиля кода - один отступ в строку между переменными и методами (между каждым)

2024-07-11 13:30 UTC, liroykaz commented on src/main/java/com/niiazov/usermanagement/controllers/RolesController.java
>  @RequestMapping("/users/{userId}/roles")
обычно контроллер мапят как /users, а далее мапят все методы. Повышает читабельность

2024-07-11 13:30 UTC, liroykaz commented on src/main/java/com/niiazov/usermanagement/controllers/RolesController.java
> +    public ResponseEntity<HttpStatus> updateUserRoles(@PathVariable Long userId, @RequestBody @Valid Set<RoleDTO> roleDTOs, BindingResult bindingResult) {
лучше избегать длинных строк. Лучше каждый параметр с аннотацией переносить на новую строку:
```
updateUserRoles(@PathVariable Long userId, 
                              @RequestBody @Valid Set<RoleDTO> roleDTOs, 
                              BindingResult bindingResult)
```

2024-07-11 13:30 UTC, liroykaz commented on src/main/java/com/niiazov/usermanagement/services/RolesService.java
> +                .map(dto -> roleRepository.findByName(dto.getName()).orElseGet(() -> {
мелочь, но если у нас будет 100 ролей, то мы сделаем 100 запросов. Лучше сделать запрос типо select * from roles r where r.name in :namesList. И далее уже с коллекцией работать

2024-07-11 13:30 UTC, liroykaz commented on src/main/java/com/niiazov/usermanagement/util/ErrorsUtil.java
> +// Утилитарный класс для форматирования сообщений об ошибке во что-то более понятное
Комментарии нужны там, где код непонятен) Хороший код не нужно комментировать. Если хочешь сделать описание класса, лучше документировать его через /** */ в начале класса. Это потом можно будет спарсить с помощью всяких утилит ну и в целом хорошая практика

2024-07-11 13:30 UTC, liroykaz commented on src/main/java/com/niiazov/usermanagement/util/ErrorsUtil.java
> +// Утилитарный класс для форматирования сообщений об ошибке во что-то более понятное
для всех аналогичных комментов актуально

2024-07-11 13:30 UTC, liroykaz commented on src/main/java/com/niiazov/usermanagement/util/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler {
контроллер адвайс для разных типов исключений хорошая практика - лайк)

2024-07-11 13:30 UTC, liroykaz commented on src/main/java/com/niiazov/usermanagement/util/ResourceNotFoundException.java
> +package com.niiazov.usermanagement.util;
можно педедж переименовать в exceptions, ну или перенести исключения в такой пакет

2024-07-11 13:30 UTC, liroykaz commented on src/main/java/com/niiazov/usermanagement/util/UserErrorResponse.java
> +    public String getMessage() {
юзай ломбок) Полезные аннотации @Data @Builder, сразу генерят геттеры/сеттеры/туСтринги и другое

2024-07-12 12:13 UTC, valkrisd commented on src/main/java/com/niiazov/usermanagement/controllers/ProfilesController.java
> +        Profile profile = profilesService.findProfile(userId);
поправил

2024-07-12 12:13 UTC, valkrisd commented on src/main/java/com/niiazov/usermanagement/controllers/RolesController.java
> +    @Autowired
поправил

2024-07-12 12:14 UTC, valkrisd commented on src/main/java/com/niiazov/usermanagement/controllers/RolesController.java
>  @RequestMapping("/users/{userId}/roles")
поправил

2024-07-12 12:14 UTC, valkrisd commented on src/main/java/com/niiazov/usermanagement/controllers/RolesController.java
> +    public ResponseEntity<HttpStatus> updateUserRoles(@PathVariable Long userId, @RequestBody @Valid Set<RoleDTO> roleDTOs, BindingResult bindingResult) {
поправил

2024-07-12 12:14 UTC, valkrisd commented on src/main/java/com/niiazov/usermanagement/services/RolesService.java
> +                .map(dto -> roleRepository.findByName(dto.getName()).orElseGet(() -> {
поправил
теперь делается только один запрос

2024-07-12 12:14 UTC, valkrisd commented on src/main/java/com/niiazov/usermanagement/util/ErrorsUtil.java
> +// Утилитарный класс для форматирования сообщений об ошибке во что-то более понятное
убрал мусорные комменты

2024-07-12 12:15 UTC, valkrisd commented on src/main/java/com/niiazov/usermanagement/util/ResourceNotFoundException.java
> +package com.niiazov.usermanagement.util;
вынес в отдельный пакет

2024-07-12 12:15 UTC, valkrisd commented on src/main/java/com/niiazov/usermanagement/util/UserErrorResponse.java
> +    public String getMessage() {
заюзал)

2024-07-19 08:51 UTC, valkrisd commented on src/main/java/com/niiazov/usermanagement/services/UserActivationTokensService.java
> +    private static final LocalDateTime TOKEN_VALIDITY_IN_MINUTES = LocalDateTime.now().plusMinutes(60);
Да, ты прав. Вынес количество минут в константу, а метод now() теперь вызывается из метода генерации токена

2024-07-19 14:52 UTC, valkrisd commented on src/main/java/com/niiazov/usermanagement/services/UserActivationTokensService.java
> +    private static final String EMAIL_FROM = "noreply@course-space.com";
добавил константу в конфиг и аннотировал при помощи @value + добавил application.yml в gitignore

2024-07-19 14:58 UTC, valkrisd commented on src/main/resources/db/migration/V1__Create_tables.sql
> +CREATE TABLE "user" (
Добавил файл миграции с инсертами тестовых данных

2024-07-25 18:16 UTC, liroykaz approved these changes

2024-07-30 07:17 UTC, merged